### ISSUE TITLE
Sensor not available in energy dashboard

### ISSUE THREAD

**Issue by PWithaarImproveQS** [reharmsen/hass-youless-component#13]
The sensors of the youless cannot be selected in the energy dashboard. When configuring the dashboard I can see my DSMR meter, but none of the Youless sensors are there. 

https://www.home-assistant.io/more-info/statistics/

**Comment by reharmsen** [comment]
Official/build in integration is live.. I am closing this custom repo and this issue

Please use the official integration and report any issues there.
