### ISSUE TITLE
Setting to change S0 Port to a water meter

### ISSUE THREAD

**Issue by Veldkornet** [reharmsen/hass-youless-component#8]
Could you add the ability to use the s0 input as a water meter instead. Maybe a boolean in the settings or something?

Currently, I use a [Pulssensor Cyble voor watermeters Itron](https://www.homewizard.nl/pulsesensor-cyble-voor-watermeters-itron) connected to the s0 port. I just modified the sensor.py and just changed the labels (for example, below). I checked with Youless themselves who confirmed that this provides the correct data.

```
    'cs0': ['Water Meter', 'water_meter', 'm3', 'mdi:gauge', 'energy.png'],
    'ps0': ['Current Water usage', 'current_water_usage', 'L/min', 'mdi:water', 'water.png']
```

**Comment by AlwinHummels** [comment]
> Could you add the ability to use the s0 input as a water meter instead. Maybe a boolean in the settings or something?
> 
> Currently, I use a [Pulssensor Cyble voor watermeters Itron](https://www.homewizard.nl/pulsesensor-cyble-voor-watermeters-itron) connected to the s0 port. I just modified the sensor.py and just changed the labels (for example, below). I checked with Youless themselves who confirmed that this provides the correct data.
> 
> ```
>     'cs0': ['Water Meter', 'water_meter', 'm3', 'mdi:gauge', 'energy.png'],
>     'ps0': ['Current Water usage', 'current_water_usage', 'L/min', 'mdi:water', 'water.png']
>

Does this work and give it correct readings?
how can i put my add my watermetervalue?
Hope you can put me the right way

**Comment by Veldkornet** [comment]
The readings are correct. I checked this work around with Youless directly. 

The initial watermeter reading I think I just set via the developer tools once off, it was a while back...

**Comment by AlwinHummels** [comment]
Thank for your reply I gonna test it here this week

**Comment by reharmsen** [comment]
Sorry for the slow response.

As I am not really a python or home assistant component developer, I will not implement this.
In #9 it is stated a native youless integration is being worked on.
I would recommend filing a feature request to home assistant core when the integration is ready.
